### PR TITLE
add configure switch to be able to select GraphicsMagick over ImageMagick

### PR DESCRIPTION
**Pull request by tgurr**

### CODE REVIEW

**Comment by tgurr** [comment]
As discussed in https://github.com/ldo/dvdauthor/issues/24. 

There needs to be an option to prefer GraphicsMagick over ImageMagick since we need to be able to select one or another at build time if both are installed on the system depending on the users choices.

I've tested various combinations, having the two Magicks installed and not installed and the configure options enabled or disabled. 

The only downside I see is that now when not passing any option to configure it doesn't additonally check for GraphicsMagick as well. I'm no autotools expert so maybe there's a better solution for this.

**Comment by tgurr** [comment]
Maybe a saner approach would be to just add two new options --enable/disable-{graphics,image}magick and by default having --enable-imagemagick and --disable-graphicsmagick. So you could either switch the magick support off completely (and not having any automagick like we have at the moment) or select which one you want and disable the other one.

**Comment by ldo** [comment]
OK, what I have done is take out the automatic inclusion of ImageMagick or GraphicsMagick, and require you to now specify `--with-imagemagick` or `--with-graphicsmagick` to the `configure` script if you want one of them. See if you prefer that.

**Comment by ldo** [comment]
Oops, didn’t carefully read the documentation for [`AC_ARG_WITH`](https://www.gnu.org/software/autoconf/manual/autoconf.html#External-Software). Try it now.

**Comment by tgurr** [comment]
Works fine for me now, thanks! I'm closing my pull request now that it is obsolete.

**Pull request closed without merging**
